apiVersion: v1
kind: PersistentVolume
metadata:
  name: hmk-uk-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: "vol-0b8c6dcdf8e766093"
    fsType: ext4